spring:
  application:
    name: mic-provider-user
  datasource:
    url: jdbc:mysql://localhost:3306/mic-frame?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        service: ${spring.application.name}
    discovery:
    server-addr: 127.0.0.1:8848

server:
  port: 8090

pagehelper:
  auto-dialect: mysql

mybatis-plus:
  mapper-locations: "classpath*:/mapper/**/*.xml"
  type-aliases-package: com.mic.user.model.bean # 扫描的包路径
  global-config:
    banner: false # 关闭打印mybatis-plus的LOGO
    db-config:
      logicDeleteField: deleted
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  executor-type: batch
