server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mic-frame?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  application:
    name: mic-user-center
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ${spring.application.name}
  redis:
    host: localhost
    port: 6379


#logging:
#  level:
#    com.feign.consumerdemo1.feign: DEBUG

feign:
  # Feign Apache HttpClient 配置项，对应 FeignHttpClientProperties 配置属性类
  httpclient:
    enabled: false # 是否开启。默认为 true
    max-connections: 200 # 最大连接数。默认为 200
    max-connections-per-route: 50 # 每个路由的最大连接数。默认为 50。router = host + port
    connection-timeout: 1
  okhttp:
    enabled: true

encrypt:
  key-store:
    location: classpath:zlt.jks
    secret: zlt!@#$
    alias: zlt
mic:
  oauth2:
    token:
      store:
        type: redis

  tenant:
    enable: true
    ignore-tables:
      - oauth_client_details


