server:
  port: 8093


spring:
  application:
    name: mic-gateway
  cloud:
    ## nacos 配置
    nacos:
      discovery:
        service: ${spring.application.name}
        server-addr: 127.0.0.1:8848

    ## gateway配置
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
      - id: mic-user-center # 路由的编号
        uri: lb://mic-provider-user # 路由到的目标地址
        predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
        - Path=/query/demo/test
        filters:
        - StripPrefix=1
      - id: oschina # 路由的编号
        uri: lb://mic-provider-user # 路由的目标地址
        predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
        - Path=/query/test/getUser
        filters: # 过滤器，对请求进行拦截，实现自定义的功能，对应 FilterDefinition 数组
        - StripPrefix=1
      - id: auth
        uri: lb://mic-provider-user
        predicates:
          - Path=/api-uaa/**
        filters:
          - StripPrefix=1
          - PreserveHostHeader
      - id: auth-login-page
        uri: lb://mic-user-center
        predicates:
          - Path=/login.html
        filters:
          - PreserveHostHeader
      - id: auth-login-process
        uri: lb://mic-user-center
        predicates:
         - Path=/user/login
        filters:
          - PreserveHostHeader
      - id: auth-login-token
        uri: lb://mic-user-center
        predicates:
          - Path=/oauth/token
        filters:
          - PreserveHostHeader
      - id: auth-login-authorize
        uri: lb://mic-user-center
        predicates:
          - Path=/oauth/authorize
        filters:
          - PreserveHostHeader
      - id: auth-check-process
        uri: lb://mic-user-center
        predicates:
          - Path=/oauth/check_token
        filters:
          - PreserveHostHeader
      - id: user
        uri: lb://mic-user-center
        predicates:
          - Path=/api-user/**
        filters:
          - StripPrefix=1

  main:
    allow-bean-definition-overriding: true

mic:
  swagger-agg:
    generate-routes: user,file
  oauth2:
    token:
      store:
        type: redis
  security:
    ignore:
      # 忽略认证的地址
      httpUrls: >
        /api-uaa/oauth/**,
        /api-uaa/validata/**,
        /api-uaa/css/**,
        /api-uaa/images/**,
        /api-uaa/js/**,
        /login.html,
        /user/login
    auth:
      urlPermission:
        #是否开启url级别权限
        enable: false
        #配置只进行登录认证，不进行url权限认证的api
        ignoreUrls: >
          /api-user/menus/current,
          /api-user/users/current,
          /api-log/requestStat
        #白名单
        includeClientIds:
        - webApp
      renew:
        #是否开启token自动续签（目前只有redis实现）
        enable: true
        #白名单
        includeClientIds:
        - webApp
  tenant:
    ignore-sqls:

#
#logging:
#  level:
#    reactor.netty: DEBUG
#    org.springframework.cloud.gateway: INFO   # TRACE